steps:
- name: gcr.io/cloud-builders/docker
  args:
  - image
  - build
  - -t
  - gcr.io/$PROJECT_ID/demo-app
  - .
  dir: app

- name: gcr.io/cloud-builders/docker
  args:
  - image
  - push
  - gcr.io/$PROJECT_ID/demo-app

- name: gcr.io/cloud-builders/gcloud
  args:
  - beta
  - run
  - deploy
  - demo-app
  - --image=gcr.io/$PROJECT_ID/demo-app
  - --platform=managed
  - --region=asia-northeast1
  - --allow-unauthenticated
  - --set-env-vars
  - MY_MESSAGE=HELLO INDORE!
  - --project=$PROJECT_ID


timeout: 1600s
options:
  machineType: N1_HIGHCPU_8
